# Generated by Django 3.1.4 on 2021-01-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
